CREATE TABLE
  IF NOT EXISTS usuarios (
    id INT NOT NULL AUTO_INCREMENT,
    nombre TEXT NOT NULL,
    nombre_usuario TEXT UNIQUE NOT NULL,
    email TEXT NOT NULL,
    contrasena TEXT NOT NULL,
    imagen TEXT UNIQUE NOT NULL,
    PRIMARY KEY (id)
  );

CREATE TABLE
  IF NOT EXISTS paises (
    id INT NOT NULL AUTO_INCREMENT,
    nombre TEXT UNIQUE NOT NULL,
    imagen TEXT UNIQUE NOT NULL,
    PRIMARY KEY (id)
  );

CREATE TABLE
  IF NOT EXISTS recetas (
    id INT NOT NULL AUTO_INCREMENT,
    nombre TEXT NOT NULL,
    fecha_publicacion DATE NOT NULL,
    id_usuario INT NOT NULL,
    imagen TEXT UNIQUE NOT NULL,
    pais INT NOT NULL,
    descripcion TEXT NOT NULL,
    pasos TEXT NOT NULL,
    INDEX (id_usuario),
    INDEX (pais),
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (pais) REFERENCES paises (id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (id)
  );

CREATE TABLE
  IF NOT EXISTS categorias (
    id INT NOT NULL AUTO_INCREMENT,
    nombre TEXT NOT NULL,
    PRIMARY KEY (id)
  );

CREATE TABLE
  IF NOT EXISTS ingredientes (
    id INT NOT NULL AUTO_INCREMENT,
    nombre TEXT NOT NULL,
    PRIMARY KEY (id)
  );

CREATE TABLE
  IF NOT EXISTS categorias_de_receta (
    id INT NOT NULL AUTO_INCREMENT,
    id_receta INT NOT NULL,
    id_categoria INT NOT NULL,
    INDEX (id_receta),
    INDEX (id_categoria),
    FOREIGN KEY (id_receta) REFERENCES recetas (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (id_categoria) REFERENCES categorias (id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (id)
  );

CREATE TABLE
  IF NOT EXISTS ingredientes_de_receta (
    id INT NOT NULL AUTO_INCREMENT,
    id_receta INT NOT NULL,
    id_ingrediente INT NOT NULL,
    cantidad TEXT NOT NULL,
    INDEX (id_receta),
    INDEX (id_ingrediente),
    FOREIGN KEY (id_receta) REFERENCES recetas (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (id_ingrediente) REFERENCES ingredientes (id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (id)
  );

CREATE TABLE
  IF NOT EXISTS comentarios (
    id INT NOT NULL AUTO_INCREMENT,
    id_receta INT NOT NULL,
    id_usuario INT NOT NULL,
    contenido TEXT NOT NULL,
    FOREIGN KEY (id_receta) REFERENCES recetas (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (id)
  );

INSERT INTO
  usuarios (nombre, nombre_usuario, email, contrasena, imagen)
VALUES
  (
    'Carlos',
    'Charles_01',
    'carloscastillo@uca.edu.ar',
    '1234',
    '1.jpeg'
  ),
  (
    'Francisco',
    'Fran_01',
    'franciscohernandez@uca.edu.ar',
    '8765',
    '2.jpeg'
  ),
  (
    'Samantha',
    'Sam_01',
    'SamanthaJohanson@uca.edu.ar',
    'qwe123',
    '3.jpeg'
  ),
  (
    'Virginia',
    'Vir_01',
    'virginiayunesick@uca.edu.ar',
    'zxc456',
    '4.jpeg'
  );

INSERT INTO
  paises (nombre, imagen)
VALUES
  ('Argentina', '1.jpeg'),
  ('India', '2.jpeg'),
  ('Mexico', '3.jpeg'),
  ('Nicaragua', '4.jpeg'),
  ('Estados Unidos', '5.jpeg'),
  ('Inglaterra', '6.jpeg'),
  ('Francia', '7.jpeg'),
  ('Italia', '8.jpeg'),
  ('España', '9.jpeg'),
  ('Uzbequistan', '10.jpeg'),
  ('Suecia', '11.jpeg'),
  ('Japon', '12.jpeg'),
  ('China', '13.jpeg');

INSERT INTO
  recetas (
    nombre,
    fecha_publicacion,
    id_usuario,
    imagen,
    pais,
    descripcion,
    pasos
  )
VALUES
  (
    'Arroz caldozo',
    '2023/11/03',
    1,
    'arroz-caldoso.jpeg',
    1,
    '¿Quieres disfrutar de un arroz caldoso casero? Con esta receta podrás deleitarte con este plato tradicional lleno de sabor y textura.',
    'En una olla, calentar un poco de aceite a fuego medio-alto. Agregar el pollo y cocinar hasta que esté dorado por todos lados.
	Retirar de la olla y reservar. En la misma olla, añadir la cebolla, el ajo y el morrón rojo. Cocinar hasta que estén tiernos.
	Agregar el tomate y cocinar por unos minutos hasta que se ablande. Añadir el arroz y mezclar bien con el sofrito.
	Verter el caldo de pollo en la olla y llevar a ebullición. Reducir el fuego a medio-bajo y cocinar durante 15-20 minutos
	o hasta que el arroz esté tierno y el caldo haya adquirido una textura caldosa. Volver a incorporar el pollo a la olla y cocinar por unos minutos más hasta que esté bien caliente.
	Sazonar con sal y pimienta al gusto. Servir el arroz caldoso con pollo caliente. Añadir un poco de perejil fresco picado por encima.'
  );

INSERT INTO
  categorias (nombre)
VALUES
  ('Con lactosa'),
  ('Sin lactosa'),
  ('Con gluten'),
  ('Sin gluten'),
  ('Con TACC'),
  ('Sin TACC'),
  ('Con mani'),
  ('Sin mani'),
  ('Con frutos secos'),
  ('Sin frutos secos'),
  ('Con mariscos'),
  ('Sin mariscos'),
  ('Con huevo'),
  ('Sin huevo'),
  ('Apto celiaco'),
  ('Vegetariano'),
  ('Vegano'),
  ('Pescetariano'),
  ('Carnivoro');

INSERT INTO
  ingredientes (nombre)
VALUES
  ('Aceite de Soja'),
  ('Aceite de Maiz'),
  ('Aceite de Oliva'),
  ('Aceite de Trufa'),
  ('Crema'),
  ('Yogur'),
  ('Leche'),
  ('Helado'),
  ('Queso'),
  ('Manteca'),
  ('Habichuelas'),
  ('Frijoles'),
  ('Porotos'),
  ('Garbanzos'),
  ('Guisantes'),
  ('Habas'),
  ('Lentejas'),
  ('Soja'),
  ('Hongos'),
  ('Champiñon'),
  ('Trufa'),
  ('Papa'),
  ('Jengibre'),
  ('Lechugas'),
  ('Acelga'),
  ('Alcachofa'),
  ('Batata'),
  ('Berenjena'),
  ('Brocoli'),
  ('Calabacin'),
  ('Calabaza'),
  ('Cardo'),
  ('Cebolla'),
  ('Cebollin'),
  ('Coles'),
  ('Coles de Bruselas'),
  ('Coliflor'),
  ('Endivia'),
  ('Tomate'),
  ('Zanahoria'),
  ('Esparrago'),
  ('Espinaca'),
  ('Hinojo'),
  ('Maiz'),
  ('Morron Rojo'),
  ('Morron Verde'),
  ('Morron Amarillo'),
  ('Morron Morado'),
  ('Palmito'),
  ('Pepino'),
  ('Pimiento'),
  ('Puerro'),
  ('Remolacha'),
  ('Albaricoque'),
  ('Caquis'),
  ('Aguacate'),
  ('Cereza'),
  ('Mango'),
  ('Melocotones'),
  ('Nectarina'),
  ('Ciruela'),
  ('Frutos del bosque'),
  ('Nueces'),
  ('Almendras'),
  ('Avellanas'),
  ('Mani'),
  ('Membrillo'),
  ('Peras'),
  ('Manzanas'),
  ('Uvas'),
  ('Frambuesa'),
  ('Fresa'),
  ('Frutilla'),
  ('Granada'),
  ('Higos'),
  ('Kiwi'),
  ('Limon'),
  ('Mandarina'),
  ('Melon'),
  ('Naranja'),
  ('Piña'),
  ('Platano'),
  ('Banana'),
  ('Pomelo'),
  ('Sandia'),
  ('Cereales'),
  ('Harina 00'),
  ('Harina 000'),
  ('Harina 0000'),
  ('Harina Leudante'),
  ('Harina de Arroz'),
  ('Harina de Cebada'),
  ('Harina de Centeno'),
  ('Harina de Maiz'),
  ('Harina de Garbanzos'),
  ('Arroz'),
  ('Pasta'),
  ('Atun'),
  ('Anchoa'),
  ('Bacalao'),
  ('Besugo'),
  ('Bonito'),
  ('Boqueron'),
  ('Caballa'),
  ('Chicharro'),
  ('Corvina'),
  ('Dorada'),
  ('Lenguado'),
  ('Lubina'),
  ('Merluza'),
  ('Mero'),
  ('Palometa'),
  ('Pejerrey'),
  ('Rape'),
  ('Rodaballo'),
  ('Salmon'),
  ('Sardina'),
  ('Trucha'),
  ('Camaron'),
  ('Cigala'),
  ('Gamba'),
  ('Langostino'),
  ('Percebe'),
  ('Almeja'),
  ('Calamar'),
  ('Mejillon'),
  ('Ostra'),
  ('Pulpo'),
  ('Sepia'),
  ('Vieira'),
  ('Carne de Cordero'),
  ('Carne de Oveja'),
  ('Carne de Ternera'),
  ('Carne de Buey'),
  ('Carne de Caballo'),
  ('Carne de Cabra'),
  ('Carne de Cerdo'),
  ('Carne de Vaca'),
  ('Pollo'),
  ('Huevo'),
  ('Clara'),
  ('Yema'),
  ('Cerveza Rubia'),
  ('erveza Roja'),
  ('Cerveza Negra'),
  ('Sidra'),
  ('Licor'),
  ('Vino blanco'),
  ('Vino tinto'),
  ('Vino rosado'),
  ('Whisky'),
  ('Cafe'),
  ('Agua'),
  ('Agua mineral'),
  ('Agua gasificada'),
  ('Jugo de Naranja'),
  ('Jugo de Limon'),
  ('Pimienta'),
  ('Achiote'),
  ('Agracejo'),
  ('Ajenuz'),
  ('Ajo'),
  ('Albahaca'),
  ('Alcaravea'),
  ('Angélica'),
  ('Anís'),
  ('Anís Estrellado'),
  ('Apio'),
  ('Azafrán'),
  ('Canela'),
  ('Cardamomo'),
  ('Carom'),
  ('Casia'),
  ('Cebolla deshidratada'),
  ('Cebollino'),
  ('Chile'),
  ('Chiles mexicanos'),
  ('Cilantro'),
  ('Clavo'),
  ('Comino'),
  ('Cúrcuma'),
  ('Dashi no moto'),
  ('Enebro'),
  ('Eneldo'),
  ('Epazote'),
  ('Estragón'),
  ('Fenogreco'),
  ('Galangal'),
  ('Granos del paraíso'),
  ('Guindilla ojo de pájaro'),
  ('Haba tonka'),
  ('Hierba limón'),
  ('Hierbabuena'),
  ('Hinojo'),
  ('Hoja de curry'),
  ('Laurel'),
  ('Lirio deshidratado'),
  ('Maca'),
  ('Macis'),
  ('Mahaleb'),
  ('Mango verde deshidratado'),
  ('Mejorana'),
  ('Menta'),
  ('Mezcla de 5 especias china'),
  ('Mezclas herbes de provence'),
  ('Mostaza'),
  ('Nigela sativa'),
  ('Nueces areca'),
  ('Nuez moscada'),
  ('Orégano'),
  ('Perejil'),
  ('Pimentón'),
  ('Pimienta'),
  ('Pimienta blanca'),
  ('Pimienta de cayena'),
  ('Pimienta de Guinea'),
  ('Pimienta de Jamaica'),
  ('Pimienta de Sichuan'),
  ('Pimienta larga'),
  ('Pimienta negra'),
  ('Pimienta timiz'),
  ('Romero'),
  ('Sal'),
  ('Sal de ajo'),
  ('Sal de apio'),
  ('Salvia'),
  ('Satureja'),
  ('Semilla de amapola'),
  ('Semilla de apio'),
  ('Semilla de Chía'),
  ('Sésamo'),
  ('Spirulina'),
  ('Tamarindo'),
  ('Tomillo'),
  ('Vainilla'),
  ('Yuzu'),
  ('Zumaque');

INSERT INTO
  ingredientes_de_receta (id_receta, id_ingrediente, cantidad)
VALUES
  (1, 2, '1 chorro'),
  (1, 139, '1 pechuga'),
  (1, 33, '1 unidad'),
  (1, 162, '1 diente'),
  (1, 45, '1/2 unidad'),
  (1, 39, '1 unidad'),
  (1, 96, '1 taza'),
  (1, 223, 'Una pizca'),
  (1, 213, 'Una pizca'),
  (1, 211, 'Unas hojas');
